package util;

public enum RequestType {
    SHOW_REGISTERED_USERLIST, SHOW_ACTIVE_USERLIST, SHOW_MY_FILES, SHOW_SHARED_FILES, FILE_REQUEST, SHOW_FILE_REQUESTS, SHOW_MESSAGES, UPLOAD_INITIATION, REQUESTED_UPLOAD_CROSSCHECK, DOWNLOAD_REQUEST, DOWNLOAD_REQUEST_RESPONSE, LOGOUT;
}